### ISSUE TITLE
add readme to dockerhub

### ISSUE THREAD

**Issue by Licenser** [wayfair-tremor/tremor-runtime#109]
https://hub.docker.com/r/tremor/tremor has no readme, @Agares pointed out it would help people.

from https://github.com/wayfair-tremor/tremor-www-docs/issues/9
> Would you mind also adding more details on the dockerhub page? Currently the overview is empty, would be great to at least have information about the distro that the image is based on :)

We should add one

**Comment by Licenser** [comment]
Added a readme https://hub.docker.com/repository/docker/tremorproject/tremor

**Comment by Agares** [comment]
Thank you! Would you mind also documenting where does the Dockerfile live? I assume it's this one: https://github.com/wayfair-tremor/tremor-runtime/blob/master/Dockerfile but that's only a guess :)

**Comment by Licenser** [comment]
That's an excellent idea! I didn't think of that :) I added it!
