### ISSUE TITLE
Tremor is logging too much data at "INFO" level  for Onramp Kafka consumer

### ISSUE THREAD

**Issue by anuprout** [wayfair-tremor/tremor-runtime#110]
**Problem**
Hi, It was noticed that Tremor is logging a lot of offset commit messages . These messages are logged every 5 seconds based on the current auto commit settings. However these messages are logged under "INFO" level which may not be wanted.

Here are the sample logs.
2020-03-06T15:50:03.634429051+00:00 INFO tremor_runtime::onramp::kafka - Offsets committed successfully
2020-03-06T15:50:08.662264942+00:00 INFO tremor_runtime::onramp::kafka - Offsets committed successfully

**Steps**

1. Open the Tremor log for an instance where an onramp kafka consumer is used.
2. Look for the above messages.

**Possible Solution(s)**
1. Can this be logged only when there is a failure in committing the offsets. 
2. Can it be  logged under "DEBUG" along with the offset number that gets committed. Currently even though it is logged, it does not mention the offset number which may not be useful for any troubleshooting .

**Comment by Licenser** [comment]
I think those are valid information level logs as they describe the state of the systems.

However we use log4rs which allows configuring the levels in a per module basis: https://docs.rs/log4rs/0.10.0/log4rs/ you could simply turn the level to warnings for the on-ramp module or consider turning all logs to warning for production deployments

**Comment by anuprout** [comment]
Thanks @Licenser .
