### ISSUE TITLE
Tremor reporting wrong metrics for Bucket operator

### ISSUE THREAD

**Issue by anuprout** [wayfair-tremor/tremor-runtime#167]
**Problem**
It is observed that Tremor is reporting wrong metrics for Bucket operator. It report the same count for "pass" as well as "overflow" actions. In my case I am exporting the metrics to InfluxDB with measurement name "tremor_metrics_lab_bucketing". When I pull these metrics data from InfluxDB I see the same value getting reported under "pass" as well as "overflow" for the bucket. Below is the sample data.

![image](https://user-images.githubusercontent.com/50779994/79014343-b26b8f80-7b38-11ea-8dc0-9e72e98759bf.png)

And here is the Tremor config I am using.
![image](https://user-images.githubusercontent.com/50779994/79014754-8bfa2400-7b39-11ea-9dae-a47c01779f4d.png)

**Steps**

1. Start a Tremor instance with a runtime and bucket operator.
2. Set a rate limit and class for the events at the runtime operator.
3. Pass data below the rate limit so that everything will pass through.
4. Capture the system metrics generated for the bucket operator and check for the pass through as well as  overflow counts.

**Possible Solution(s)**

**Notes**

Output of `rustup --version`:
Output of `rustup show`:
Output of `tremor-server --version`: 0.6.1

**Comment by anupdhml** [comment]
Fixed in https://github.com/wayfair-tremor/tremor-runtime/pull/166

**Comment by anuprout** [comment]
awesome . thanks :)
