### ISSUE TITLE
Tremor "statsd" codec validation throws error for right format payload

### ISSUE THREAD

**Issue by anuprout** [wayfair-tremor/tremor-runtime#235]
**Problem**

The statsd codec validation is not able to parse payload with valid statsd format. The rate field should be optional while it expects that. Even though by passing the rate filed, it errors out .Below are the sample payloads and corresponding errors Tremor throws.

sam:7|c
ERROR tremor_runtime::onramp::prelude - [Codec] Invalid statsd metric

sam:7|c|@0.1
ERROR tremor_runtime::onramp::prelude - [Codec] invalid float literal

**Steps**

1. starts a Tremor service UDP onramp with statsd codec
2. Send the above UDP payload to the Tremor service

**Possible Solution(s)**

**Notes**

Output of `rustup --version`:
Output of `rustup show`:
Output of `tremor-server --version`: 0.7.3

**Comment by anupdhml** [comment]
Closing this out, since this turned out to be a case of payloads ending in a new line, which can be handled with the lines preprocessor: https://github.com/wayfair-tremor/tremor-runtime/pull/244#issuecomment-640784326
