### ISSUE TITLE
The API /pipeline/{id} is throwing HTTP 404

### ISSUE THREAD

**Issue by anuprout** [wayfair-tremor/tremor-runtime#374]
**Problem**
It is observed that the API /pipeline/{id} is throwing HTTP 404 even though the id exists. The /pipeline returns a list of pipeline ids Tremor runtime has. However when a particular id detail is requested, it throws HTTP 404 error. 

[***@tremormetricsreceiver***:~] % curl -i http://tremormetricsreceiver***.com:9898/pipeline    
HTTP/1.1 200 OK
content-length: 43
date: Fri, 31 Jul 2020 20:04:00 GMT
content-type: application/json
["metrics-enrich","system::metrics","**main"**]%    
                        
[***@tremormetricsreceiver***:~] % curl -i http://tremormetricsreceiver***.com:9898**/pipeline/main
**HTTP/1.1 404 Not Found**
content-length: 0
date: Fri, 31 Jul 2020 20:04:05 GMT

**Steps**

1. Start Tremor with a pipeline
2. Query the pipeline using the /pipeline/{id} API.

**Possible Solution(s)**

**Notes**

Output of `rustup --version`:
Output of `rustup show`:
Output of `tremor-server --version`: 0.8.2

**Comment by Licenser** [comment]
I think this is fixed on @darach's branch already :) let's double-check when he's back from vacation.

**Comment by Licenser** [comment]
Fixed by #409 thanks @mfelsche !
