### ISSUE TITLE
evaluate snmalloc as a mimalloc replacement

### ISSUE THREAD

**Issue by Licenser** [wayfair-tremor/tremor-runtime#65]
**Describe the problem you are trying to solve**

In our use-case we're heavily dependant on inter-thread communication, events arrive in the onramp thread, processed in the pipeline thread and send in the offramp thread. This leads to data being allocated (mostly) in the onramp thread, modified in the pipeline thread and deallocated in the offramp thread. This producer-consumer style (as the snmalloc paper calls it) data flow can benefit greatly from the optimizations done in snmalloc.

**Describe the solution you'd like**

We should evaluate, benchmark, test and eventually adopt snmalloc as a replacement for mimalloc.

**Comment by mjp41** [comment]
Sounds like a perfect fit for snmalloc.
