### ISSUE TITLE
logging message payload when "influx" codec validation fails

### ISSUE THREAD

**Issue by anuprout** [wayfair-tremor/tremor-runtime#75]
Hi, I am looking for some logging of the actual payload when a message fails at codec validation. Right now it is logging the below info for "influx" codec validation.

```
2020-02-26T13:28:37.125891449+00:00 ERROR tremor_runtime::onramp::prelude - [Codec] invalid digit found in_ string
```

**Describe the solution you'd like**
It would be great if the actual "invalid" character is printed at "ERROR" level and the entire payload can be printed at "DEBUG" level.

Thanks

(edit by @Licenser add code blocks for readability)

**Comment by Licenser** [comment]
That’s an excellent idea! It might be even worth it always logging the offender as they should be rare
