### ISSUE TITLE
Improve vscode dev container experience

### ISSUE THREAD

**Issue by darach** [wayfair-tremor/tremor-runtime#86]
**Describe the problem you are trying to solve**

Currently the dev container support for tremor is good but working natively on OS X
and natively in the dev container requires some compromises which cost developer
time. The enhancements below should reduce the context switching overheads

**Describe the solution you'd like**

- [x] Add support for linux-tools perf
- [x] Add support for Brendan Gregg's flamegraph
- [x] Add support for valgrind
- [x] Allow Mac OS X and vsc dev container to co-exist with different cargo target paths
- [x] Integrate perf/flame/valgrind with benchmark system
- [x] Investigate dev container setup tweaks for Mac Os X dev environments

**Notes**

- [ ] Optional. Consider adding convenience scripts as appropriate

**Comment by darach** [comment]
Resolved by #99 with convenience scripts to be added

**Comment by Licenser** [comment]
closing this as it's marked as resolved in the prior comment
